config/routes.rb
Rails.application.routes.draw do
  resources :comments, only: [:edit, :update]
  resources :stars, only: [:show, :index] do
    resources :palaces, only: [:index, :show] do
      resources :relationships, only: [:new, :create, :update, :edit, :destroy]
      resources :comments, except: :index
    end
    resources :comments, except: :index
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :charts

  devise_for :members, controllers: {
    omniauth_callbacks: 'auth/omniauth_callbacks'
  }

  root 'charts#index'
end

app/models/chart.rb
class Chart < ActiveRecord::Base
  extend FriendlyId
  friendly_id :slug_candidates, use: :slugged

  belongs_to :member, touch: true

  before_validation :build_chart!
  validates :zi_wei_id, presence: true

  #  Branch assignments for palaces are in reverse order
  #  beginning with the branch of the Ming palace.
  def palaces
    Rails.cache.fetch "#{cache_key}/palaces" do
      branches = Branch.all.to_a.rotate(ming_id).reverse

      Palace.all.zip(branches).map do |palace, branch|
        ChartPalace.new palace: palace, location: branch, stars: stars_in_branch_palace(branch)
      end
    end
  end

  def stars_in_branch_palace(branch)
    Star.all.select do |star|
      self["#{star.symbol_name}_id"] == branch.id
    end
  end

  def build_chart!
    lunar_date = LunarDate.from_solar_date(solar_date)
    self.attributes = lunar_date.stored_attributes
    self.attributes = ChartBuilder.new(self).attributes
  end

  concerning :DateCorrection do
    def dst?
      if time_zone?
        dob.in_time_zone.dst?
      else
        false
      end
    end

    def local_dob
      if time_zone?
        dob.in_time_zone(time_zone)
      else
        dob
      end
    end

    def corrected_dob
      if time_zone?
        d = dob.in_time_zone(time_zone)
        if d.dst?
          d = d - 1.hours
        end
        d
      else
        dob
      end
    end

    def solar_date
      date = corrected_dob
      if date.hour == 0
        hour = 0
      elsif date.hour == 23
        hour = 23
      elsif date.hour % 2 == 0
        hour = date.hour - 1
      else
        hour = date.hour
      end
      DateTime.parse(date.strftime("%Y-%m-%d #{hour}:00"))
    end
  end

  concerning :DisplayProperties do
    def person_name
      "#{first_name} #{last_name}"
    end

    def search_text
      "#{person_name} #{year.stem.element} #{year.branch.animal} #{hour.stem.element} #{hour.branch.animal}".downcase
    end

    def dob_year
      dob.year if dob
    end

    def dob_month
      dob.month if dob
    end

    def dob_day
      dob.day if dob
    end

    def dob_time
      dob
    end

    def year
      @year ||= Pillar.find_by_ordinal(year_id)
    end

    def month
      @month ||= Pillar.find_by_ordinal(month_id)
    end

    def day
      @day ||= Pillar.find_by_ordinal(day_id)
    end

    def hour
      @hour ||= Pillar.find_by_ordinal(hour_id)
    end

    def name
      hr = hour.branch.ordinal
      solar_date.strftime('%Y-%m-%d-' + (hr < 10 ? "0#{hr}" : hr).to_s)
    end
  end

  concerning :FriendlyId do
    def slug_candidates
      [
        [:person_name],
        [:person_name, :member_id]
      ]
    end
    included do
      def self.find_by_slug!(slug)
        friendly.find(slug)
      end
    end
  end

  def method_missing(method, *args)
    star_name = method.to_s.gsub(/=/, '').to_sym
    super unless star_name.in? Star::STAR_PINYIN
    ActiveSupport::Deprecation.warn("Called nonexistent class method #{method} on Chart.")
    if method.to_s =~ /=$/
      branch = args.first
      self["#{star_name}_id"] = branch.ordinal
    else
      Branch.find_by_ordinal self["#{star_name}_id"]
    end
  end
end

app/controllers/charts_controller.rb
class ChartsController < ApplicationController
  load_and_authorize_resource :chart, except: [:create, :index, :update], find_by: :slug
  respond_to :json

  def index
    @charts = Rails.cache.fetch "charts-#{current_member.cache_key}" do
      current_member.charts
    end

    @cache_key = "#{@charts.cache_key}/#{current_member.cache_key}/#{params[:search] || 'none'}"

    if params[:search]
      regexp = Regexp.new params[:search], 'i'
      @charts = @charts.select{|t| t.search_text =~ regexp}
    end

    if conservative_stale? @cache_key
      render :index
    end
  end

  def destroy
    @chart.destroy
    redirect_to charts_path
  end

  def show
    @year = 'base'
    if params[:year]
      @year = params[:year]
      ming_branch = Branch.find_by_english_name(@year)

      @chart.palaces.sort{|t, u| t.location.ordinal <=> u.location.ordinal}.each_with_index do |chart_palace, i|
        chart_palace.palace = Palace.find_by_ordinal(((chart_palace.palace.id + ming_branch.ordinal - @chart.ming_id - 1) % 12) + 1)
      end
    end

    respond_to do |format|
      format.html {
        render :show
      }
      format.pdf {
        pdf = ChartPdf.new(@chart, view_context)
        send_data pdf.render, filename: pdf.file_name, type: pdf.mime_type, disposition: 'inline'
      }
    end
  end

  def update
    @chart = current_member.charts.friendly.find(params[:id])
    @chart.attributes = chart_params.except(*DATE_PARAMS)
    @chart.dob = replace_date_parts_with_date_time
    @chart.save!
    redirect_to @chart
  end

  DATE_PARAMS = [ :dob_year, :dob_month, :dob_day, :dob_time]

  def create
    @chart = current_member.charts.new chart_params.except(*DATE_PARAMS)
    @chart.dob = replace_date_parts_with_date_time
    @chart.save
    redirect_to @chart
  end

  def replace_date_parts_with_date_time
    Time.use_zone @chart.time_zone do
      values = chart_params.slice(*DATE_PARAMS).values
      puts values.inspect
      return Time.zone.parse [values[0..2].join('/'), values.last].join(' ')
    end
  end

  def chart_params
    params.require(:chart).permit(:first_name, :last_name, :yin_yang, :time_zone, *DATE_PARAMS)
  end

  def date_param
    params.require(:chart).permit("year", "month(2i)", "day", "time")
  end
end

app/helpers/charts_helper.rb
module ChartsHelper
  def palace_animal_display(chart_palace)
    [chart_palace.location.char, chart_palace.location.pinyin, chart_palace.location.animal].join(' ')
  end

  def borrowed_stars(palace)
    @chart.palaces.find{ |other_palace|
      other_palace.location == palace.location.diametric
    }.major_stars.sort_by &:rank
  end

  def major_stars(palace)
    palace.major_stars.sort_by &:rank
  end

  def minor_stars(palace)
    palace.minor_stars.sort_by &:rank
  end

  ORDINATORS = ['th', 'st', 'nd', 'rd']

  def ordinate(number)
    content_tag :span do
      concat number.to_s
      concat content_tag :sup, (ORDINATORS[number] || 'th')
    end
  end
end

app/views/charts/_form.html.slim
.row: *col_sizes(lg: 6, md: 8, sm: 10, xs: 12, offset: {lg: 3, md: 2, sm: 1, xs: 0})
  = vertical_form_for(@chart) do |f|
    = f.text_input :first_name, class: 'border-radius-2', label: false
    = f.text_input :last_name, class: 'border-radius-2', label: false
    .form-group: .input-group
      span.input-group-addon.border-left-radius-2 Yin/Yang
      = f.collection_select :yin_yang, [['Yin (Female)', 'yin'], ['Yang (Male)', 'yang']], :last, :first, {}, class: 'form-control'
      span.input-group-addon.border-right-radius-2
        i.fa.fa-female
        | /
        i.fa.fa-male

    .input-group
      = f.text_field :dob_year, placeholder: 'Year', class: 'form-control border-left-radius-2', autocomplete: 'off'
      = f.collection_select :dob_month, months, :last, :first, class: 'form-control', default: nil, include_blank: true
      /= f.date_select :dob_month, discard_year: true, discard_day: true, class: 'form-control', default: nil, include_blank: true, placeholder: 'Month'
      = f.text_field :dob_day, placeholder: 'Day', class: 'form-control'
      = f.time_field :dob_time, class: 'form-control border-right-radius-2'
    .input-group.m-t-1.w-100
      span.input-group-addon.border-left-radius-2 Time Zone
      = f.time_zone_select :time_zone, nil, include_blank: true
      span.input-group-addon.border-right-radius-2
        i.fa.fa-globe

    button type="submit" class='w-100 btn border-radius-2 m-t-1 btn-social btn-primary'
      i class="fa fa-floppy-o"
      .w-100.text-xs-center Save

app/views/charts/edit.html.slim
h2.text-xs-center Edit Chart

= render partial: 'form'

app/views/charts/index.html.slim
- cache "view-#{@cache_key}" do
  h4.text-xs-center My Charts

  .row: *col_sizes(lg: 4, md: 6, sm: 8, xs: 12, offset: {lg: 4, md: 3, sm: 2, xs: 0})
    = form_tag charts_path, method: 'get' do
      .form-group
        .input-group.w-100.card-like.border-radius-2
          / .input-group-addon.border-left-radius-2 $
          input.border-left-radius-2#chart-search.form-control name="search" placeholder="Search: 'charlie' or 'wood monkey'" value=params[:search] autocomplete="off" type="text" /
          .input-group-addon.border-right-radius-2
            button type="submit" class='form-control btn btn-sm'
              i.fa.fa-search

  .row: *col_sizes(lg: 8, sm: 10, xs: 12, offset: {lg: 2, sm: 1, xs: 0})
    .card-like.p-x-1.border-radius-1
      .table-list
        .row.p-y-1.border-top-radius-1
          .col-sm-4.col-xs-8 Name
          .col-sm-3.hidden-xs-down Year
          .col-sm-3.hidden-xs-down Hour
          .col-sm-2.col-xs-4 Buttons
        .table-body
          - @charts.each do |chart|
            .row.p-y-1.linkable[
              data-href=chart_path(chart)
              data-search_text=chart.search_text
              ]
              .col-md-4.col-xs-8: h5.m-b-0= chart.person_name
              .col-sm-1.hidden-sm-down= chart.dob.strftime('%Y')
              .col-xs-2.hidden-sm-down
                = chart.year.stem.element.titleize
                | &nbsp;
                = chart.year.branch.animal.titleize
              .col-xs-2.hidden-sm-down
                = chart.hour.stem.element.titleize
                | &nbsp;
                = chart.hour.branch.animal.titleize
              .col-md-3.col-xs-4
                = link_to chart_path(chart), method: :delete, :'data-turbolinks' => "false", :'data-confirm' => 'Really?', class: 'pull-xs-right' do
                  i.fa.fa-trash-o.m-l-1
                = link_to chart_path(chart, format: :pdf), class: 'pull-xs-right' do
                  i.fa.fa-file-pdf-o.m-l-1
                = link_to [:edit, chart], class: 'pull-xs-right' do
                  i.fa.fa-pencil.m-l-1
                = link_to chart, class: 'pull-xs-right' do
                  i.fa.fa-folder-open-o.m-l-1

app/views/charts/new.html.slim
h2.text-xs-center New Chart

= render partial: 'form'

app/views/charts/show.html.slim
.row
  .col-lg-7
    .chart_display.card-like.border-radius-05
      - cache "#{@chart.cache_key}/#{params[:year]}" do
        .chart_title
          h1.name.text-xs-center.p-t-1= link_to @chart.person_name, @chart
          .text-xs-center
            = @chart.local_dob.strftime '%Y  %B %d, %I:%M %p'
            - if @chart.time_zone?
              - if @chart.local_dob.dst?
                sup *
            - else
              sup +
          .text-xs-center
            =ordinate(@chart.lunar_month)
            - if @chart.leap
              | &nbsp;month (leap) /&nbsp;
            - else
              | &nbsp;month /&nbsp;
            = ordinate(@chart.day_of_month) + " day"
          .text-xs-center= "Inner Element: #{@chart.inner_element.titleize}"
          .row.pillars.m-x-0.w-100
            - %w(year month day hour).each do |pillar|
              .col-xs-3.text-xs-center.p-x-0
                h5.pillar_name= pillar.titleize
                .chinese= @chart.send(pillar).chinese
                .pinyin= @chart.send(pillar).pinyin
                .english= @chart.send(pillar).name


        .palaces
          - @chart.palaces.each do |chart_palace|
            .palace class=chart_palace.location.animal data-palace-id=chart_palace.palace.to_param
              .palace_name.tooltippy class=chart_palace.location.animal data-palace-id=chart_palace.palace.to_param data-title='Click for details'
                h5.m-b-0.p-a-05.name= "#{chart_palace.ordinal}. #{chart_palace.name}"
                /h5.name= link_to "#{chart_palace.ordinal}. #{chart_palace.name}", palace_path(chart_palace.palace.friendly_id)
              .stars.p-x-05
                .major_stars
                  - if chart_palace.major_stars.empty?
                    = render partial: 'stars/star', collection: borrowed_stars(chart_palace), locals: {star_class: 'borrowed_star', chart_palace: chart_palace}
                  - else
                    = render partial: 'stars/star', collection: major_stars(chart_palace), locals: {star_class: 'major_star', chart_palace: chart_palace}
                .minor_stars
                  = render partial: 'stars/star', collection: minor_stars(chart_palace), locals: {star_class: 'minor_star', chart_palace: chart_palace}
                /span.palace_location= link_to palace_animal_display(chart_palace), person_path(params[:id], year: chart_palace.location.animal)
              .palace_location: span.pull-right.p-r-05= link_to chart_palace.location.animal.titleize, chart_path(@chart, year: chart_palace.location.animal)

  .col-lg-5
    .notes
      - @chart.palaces.each do |chart_palace|
        .palace-notes.hidden-xs-up id="notes-#{chart_palace.palace.to_param}"
          h3= chart_palace.name
          = render chart_palace.star_relationships